### ISSUE TITLE
Unable to vagrant ssh to centos6

### ISSUE THREAD

**Issue by bluedrag** [dockpack/dockpack#16]
`vagrant up --provider virtualbox` times out because password is needed for ssh.
Tried `vagrant` as password in the gui, did not work. 
Tried using the vagrantfile provided here and `vagrant up centos6`, did not work.
Tried `config.ssh.insert_key = false` on a basic Vagrantfile, did not work. 
Currently out of ideas, any help is appreciated, thanks!

**Comment by bbaassssiiee** [comment]
This is the general usage:

The vagrant user is created in the kickstart when you build the base box with packer.
    `packer build -only=virtualbox-iso dockpack-centos6.json`
You then add the base box to VirtualBox so you can re-use it:
    `vagrant box add --force dockpack/centos6 packer/virtualbox-centos6.box`
Then you can launch it using:
    `vagrant up centos6`

**Comment by bbaassssiiee** [comment]
For some reason a boot password is required by the box now.
